# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Make persistent changes in /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  ############################################
  # Boot / Kernel
  ############################################
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  ############################################
  # Filesystems — Btrfs root
  ############################################
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a551eedc-61b1-458b-8d4d-99e7ddcc0b1a";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd:3"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a551eedc-61b1-458b-8d4d-99e7ddcc0b1a";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:3"
      "noatime"
    ];
  };

  ############################################
  # EFI
  ############################################
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/954A-B524";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  ############################################
  # Storage dedicado para libvirt / VMs
  ############################################
  fileSystems."/var/lib/virt" = {
    device = "/dev/disk/by-uuid/06b5fe17-f758-4172-98e7-04287590a710";
    fsType = "btrfs";
    options = [
      "subvol=@DATA"
      "compress=zstd:3"
      "noatime"
    ];
  };

  ############################################
  # Swap
  ############################################
  swapDevices = [
    { device = "/dev/disk/by-uuid/6e5e19fc-82c8-4436-89c3-da8ed8cfb12b"; }
  ];

  ############################################
  # Platform
  ############################################
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
